### ISSUE TITLE
程序错误报告

### ISSUE THREAD

**Issue by greedisgoood** [shanmite/LotteryAutoScript#47]
> lottery-in-bilibili@2.1.0 start /home/runner/work/LotteryAutoScript/LotteryAutoScript
> node main.js start

(node:1834) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Authorization"]
    at ClientRequest.setHeader (_http_outgoing.js:561:3)
    at new ClientRequest (_http_client.js:251:14)
    at request (https.js:313:10)
    at HttpRequest (/home/runner/work/LotteryAutoScript/LotteryAutoScript/lib/HttpRequest.js:89:17)
    at /home/runner/work/LotteryAutoScript/LotteryAutoScript/lib/GithubAPI.js:53:13
    at new Promise (<anonymous>)
    at Object.downloadArtifacts (/home/runner/work/LotteryAutoScript/LotteryAutoScript/lib/GithubAPI.js:52:16)
    at /home/runner/work/LotteryAutoScript/LotteryAutoScript/lib/MyStorage.js:14:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1834) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1834) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by shanmite** [comment]
申请的GitHub token填对没

**Comment by greedisgoood** [comment]
果然是这个问题  谢谢
